services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"